language: php
php:
  - 5.5
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution
  - git checkout 2.0.0
  - composer update --dev
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer require nieuwenhuizen/cr:dev-master
  - cd Packages/Application
  - git clone https://github.com/keen-vantage/BuJitsuDo.Authentication.git
  - cd ../../
install:
  - mv ../BJD.Events Packages/Application
script:
  - bin/phpunit -c Packages/Application/BJD.Events/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Packages/Application/BJD.Events/UnitTests.xml --testsuite "BJD.Events tests"
  - cd Packages/Application/BJD.Events
  - ../../../bin/test-reporter